# 监控中心配置
spring:
  security:
    user:
      name: erahub
      password: erahub123
  boot:
    admin:
      ui:
        title: erahub-auth-simple服务监控中心
      discovery:
        # seata 不具有健康检查的能力 防止报错排除掉
        ignored-services: erahub-seata-server
