# 安全配置
security:
  # 验证码
  captcha:
    # 是否开启验证码
    enabled: true
    # 验证码类型 math 数组计算 char 字符验证
    type: MATH
    # line 线段干扰 circle 圆圈干扰 shear 扭曲干扰
    category: CIRCLE
    # 数字验证码位数
    numberLength: 1
    # 字符验证码长度
    charLength: 4
  # 防止XSS攻击
  xss:
    enabled: true
    excludeUrls:
      - /basicservice/notice
  # 不校验白名单
  ignore:
    whites:
      - /code
      - /auth/logout
      - /auth/login
      - /auth/smsLogin
      - /auth/xcxLogin
      - /auth/register
      - /basicservice/sms/code
      - /*/v3/api-docs
      - /csrf

spring:
  cloud:
    # 网关配置
    gateway:
      # 打印请求日志(自定义)
      requestLog: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # 认证中心
        - id: erahub-auth
          uri: lb://erahub-auth
          predicates:
            - Path=/auth/**
          filters:
            # 验证码处理
            - ValidateCodeFilter
            - StripPrefix=1
        # 系统工具
        - id: erahub-base
          uri: lb://erahub-base
          predicates:
            - Path=/tool/**
          filters:
            - StripPrefix=1
        # 系统模块
        - id: erahub-base
          uri: lb://erahub-base
          predicates:
            - Path=/system/**
          filters:
            - StripPrefix=1
        # 基础服务
        - id: erahub-base
          uri: lb://erahub-base
          predicates:
            - Path=/basicservice/**
          filters:
            - StripPrefix=1
        # 演示服务
        - id: erahub-demo
          uri: lb://erahub-demo
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
        # MQ演示服务
        - id: erahub-stream-mq
          uri: lb://erahub-stream-mq
          predicates:
            - Path=/stream-mq/**
          filters:
            - StripPrefix=1

    # sentinel 配置
    sentinel:
      # nacos配置持久化
      datasource:
        ds1:
          nacos:
            server-addr: ${spring.cloud.nacos.server-addr}
            dataId: sentinel-${spring.application.name}.json
            groupId: ${spring.cloud.nacos.config.group}
            namespace: ${spring.profiles.active}
            data-type: json
            rule-type: flow
